:service:
  :name: :hanlon_websvc_resource_api
  :type: :web_service
:config:
  :cache:
    :default_max_size: 10000
    :default_ttl: 1000
  :swagger_ui:
    :allow_access: true
    :mount_path: /docs
    :api_version: v1
    :base_path: /hanlon/api